[package]
name = "subdomain_source"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
reqwest = {version = "0.12.4", features = ["blocking"]}
serde_json = "1.0.117"
tokio = { version = "1.38.0", features = ["full"] }
util = { path = "../util" }