[package]
name = "vulnerability_scan"
version = "0.1.0"
edition = "2021"

[dependencies]
dns-lookup = "2.0.4"
reqwest = {version = "0.12.4", features = ["blocking"]}
serde = { version = "1.0.203", features = ["derive"] }
tokio = { version = "1.38.0", features = ["full"] }
util = { path = "../util" }
